### ISSUE TITLE
Dump pod logs at the end of each workload run

### ISSUE THREAD

**Issue by chaitanyaenr** [openshift-scale/workloads#36]
Each workload should dump the logs of the scalei-ci pod running the workload in the end for both pass/fail cases, this way we can see the stdout of the workload run.

**Comment by jmencak** [comment]
Yes, I agree this would be useful.  In the ideal world, every workload should be dumping the logs as it *runs* and not at the end.

**Comment by akrzos** [comment]
Ravi and I discussed this and the simple implementation that retains functionality here for CI is to set `export JOB_COMPLETION_POLL_ATTEMPTS=0` thus the ansible task completes successfully **after** the workload job is active.  The ci environment in which we intend logs to stream then runs `oc logs` to stream output into the jenkins console.  Thus `JOB_COMPLETION_POLL_ATTEMPTS` is really just for when you run the workloads locally or in an active bench-marking analysis situation.

I was unable to find a simple ansible streaming output option in the short period of time I searched.  Another potential option would be to poll `oc logs -n scale-ci-tooling --timestamps job/scale-ci-network --since-time="2019-06-21T14:10:50Z"` with an ever incrementing since-time value however it would potentially duplicate lines and the the logic to detect job completion might be tricky.

In the future we might need to add more success criteria to each workload which could exist after the job completes, anyhow I think the first idea above suffices the current requirement so let me know your thoughts.

**Comment by chaitanyaenr** [comment]
Agree with @jmencak, streaming the logs would be best but it's difficult to do it using ansible. One of the use cases for this is the CI which can be starter, dedicated or scale-ci pipeline. Alex and I had a discussion about it and one way to do it would be is to set the https://github.com/openshift-scale/workloads/blob/master/workloads/nodevertical.yml#L153 to 0 and then let the build script in the CI handle the logging part i.e stream till the job completes like https://github.com/openshift/svt/blob/master/openshift_tooling/pbench/controller.sh#L62.

**Comment by chaitanyaenr** [comment]
@akrzos proposed two solutions 1) handling it in build script like mentioned above which is the quickest way 2) write an ansible plugin to add support to stream in the future. We are going to take the first route for now.

**Comment by akrzos** [comment]
So an example of this is here - https://github.com/openshift-scale/scale-ci-pipeline/pull/14/files#diff-aed600ddce0bb20fc7addd04a6c7d615R24

Note the default for `JOB_COMPLETION_POLL_ATTEMPTS` in the job is 0.

**Comment by akrzos** [comment]
@chaitanyaenr Can we close this issue now that we have working examples to stream logs after the workload has been started?

**Comment by chaitanyaenr** [comment]
@akrzos yes, closing it.
